name: hana_bridge
from_domain: 2
to_domain: 3

topics:
  # Robot 1 communication
  robot_1/user_cmd:
    type: std_msgs/msg/String
    from_domain: 129
    to_domain: 18
    bidirectional: true
  
  robot_1/status:
    type: std_msgs/msg/String
    from_domain: 18
    to_domain: 129
    bidirectional: true



  # Robot 2 communication
  robot_2/user_cmd:
    type: std_msgs/msg/String
    from_domain: 129
    to_domain: 19
    bidirectional: true
    
  robot_2/status:
    type: std_msgs/msg/String
    from_domain: 19
    to_domain: 129
    bidirectional: true
